from enum import Enum


class Verdict(Enum):
    #: Undocumented (TODO)
    FAILED = "FAILED"
    #: Undocumented (TODO)
    OK = "OK"
    #: Undocumented (TODO)
    PARTIAL = "PARTIAL"
    #: Undocumented (TODO)
    COMPILATION_ERROR = "COMPILATION_ERROR"
    #: Undocumented (TODO)
    RUNTIME_ERROR = "RUNTIME_ERROR"
    #: Undocumented (TODO)
    WRONG_ANSWER = "WRONG_ANSWER"
    #: Undocumented (TODO)
    PRESENTATION_ERROR = "PRESENTATION_ERROR"
    #: Undocumented (TODO)
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"
    #: Undocumented (TODO)
    MEMORY_LIMIT_EXCEEDED = "MEMORY_LIMIT_EXCEEDED"
    #: Undocumented (TODO)
    IDLENESS_LIMIT_EXCEEDED = "IDLENESS_LIMIT_EXCEEDED"
    #: Undocumented (TODO)
    SECURITY_VIOLATED = "SECURITY_VIOLATED"
    #: Undocumented (TODO)
    CRASHED = "CRASHED"
    #: Undocumented (TODO)
    INPUT_PREPARATION_CRASHED = "INPUT_PREPARATION_CRASHED"
    #: Undocumented (TODO)
    CHALLENGED = "CHALLENGED"
    #: Undocumented (TODO)
    SKIPPED = "SKIPPED"
    #: Undocumented (TODO)
    TESTING = "TESTING"
    #: Undocumented (TODO)
    REJECTED = "REJECTED"
    #: Undocumented (TODO)
    HACK_SUCCESSFUL = "HACK_SUCCESSFUL"
    #: Undocumented (TODO)
    HACK_UNSUCCESSFUL = "HACK_UNSUCCESSFUL"
    #: Undocumented (TODO)
    INVALID_INPUT = "INVALID_INPUT"
    #: Undocumented (TODO)
    GENERATOR_INCOMPILABLE = "GENERATOR_INCOMPILABLE"
    #: Undocumented (TODO)
    GENERATOR_CRASHED = "GENERATOR_CRASHED"
    #: Undocumented (TODO)
    IGNORED = "IGNORED"
    #: Undocumented (TODO)
    OTHER = "OTHER"
